/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_aimove_free: (a: number, b: number) => void;
export const __wbg_alphabetaplayer_free: (a: number, b: number) => void;
export const __wbg_get_aimove_cell_index: (a: number) => number;
export const __wbg_get_aimove_score: (a: number) => number;
export const __wbg_get_alphabetaplayer_depth: (a: number) => number;
export const __wbg_set_aimove_cell_index: (a: number, b: number) => void;
export const __wbg_set_aimove_score: (a: number, b: number) => void;
export const __wbg_set_alphabetaplayer_depth: (a: number, b: number) => void;
export const alphabetaplayer_choose_move: (a: number, b: number, c: number, d: number) => number;
export const alphabetaplayer_new: (a: number) => number;
export const init: () => void;
export const __wbg_board_free: (a: number, b: number) => void;
export const __wbg_moveresult_free: (a: number, b: number) => void;
export const board_apply_move_js: (a: number, b: number, c: number, d: number) => number;
export const board_check_is_terminal: (a: number) => number;
export const board_clone_js: (a: number) => number;
export const board_get_count: (a: number, b: number) => number;
export const board_get_game_winner: (a: number) => number;
export const board_get_grid: (a: number) => [number, number];
export const board_get_legal_moves_js: (a: number, b: number) => [number, number];
export const board_get_score_js: (a: number, b: number) => number;
export const board_get_turn: (a: number) => number;
export const board_other_js: (a: number, b: number) => number;
export const board_set_grid: (a: number, b: number, c: number) => void;
export const board_set_turn: (a: number, b: number) => void;
export const board_wasm_new: () => number;
export const moveresult_board: (a: number) => number;
export const moveresult_flipped_indices: (a: number) => [number, number];
export const __wbg_get_minimaxplayer_depth: (a: number) => number;
export const __wbg_minimaxplayer_free: (a: number, b: number) => void;
export const __wbg_set_minimaxplayer_depth: (a: number, b: number) => void;
export const minimaxplayer_choose_move: (a: number, b: number, c: number, d: number) => number;
export const minimaxplayer_new: (a: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
